language: generic
dist: bionic

services:
  - docker

env:
  global:
    - VERSION=0.21.0
    
matrix:
  include:
    - env: PYBASEVER=3.6 ARCH=x86_64
    - env: PYBASEVER=3.7 ARCH=x86_64
    - env: PYBASEVER=3.8 ARCH=x86_64
    - env: PYBASEVER=3.9 ARCH=x86_64

install:
  - docker pull openturns/archlinux-mingw

script:
  - docker run -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/archlinux-mingw /io/run_docker_build.sh ${VERSION} ${PYBASEVER} ${ARCH} `id -u` `id -g`

deploy:
  provider: releases
  api_key:
    secure: cd0S+kMquh52ikvHAgLL3NZfk2mUZKZNYuh35/J1c4/QK2HsiVPmVHFQveWpPLYm+bEnFepYS3Y/MnZ2xnbFG+fmINn/pO0Dsji24dGkxLAY5pjCusfqMntwbmEZgJ3Yamwesr3N57fWUrhSXq/ltVevFxMa93Ufz5pA3LEldsqK1Loae1LE5gOIWCgXeNWdbG4NZt0p44i+Gh3HvJA7PQCyzXVPzunA8sDi3sEqUvZXQs6/mHM9QPhXColLSCsVl4nR+JWSpG+lZdbuNrqJelHzLw1WD+JdhoEwLoLnLDfvTiLlmnm0j7mKwN6ej/4KFbpBZFX30eaT9bKCluxJBWjz3k7h/NmMl5oLZ2VIWEj69rc710Ddifpx4lj9AjIEfdsnc6ph3z01gsGVzR12mVvQYwTfqGzTMK2KZSzlNX3N1cKhC3RIBQLMROw04hsey/GaQ/Gf9zq0m2ZJLa+q+fZmygNxX6bP285MAD5lqS68BqwQKEkbUMnnz7eZ1Lh1JGFNEOkblDE4xfKZsaOtaBm8uV7PgPMAenIVIKf82D9Wn0ro+o4FHQrOjnhXNL1Xq8fvbOHuh1MlLsl1RJio+X/bZT/2DsAN1+w7snz1hgb6aypxfwSc3dCqEquC3A9mhpfJD43IKEogIEKoDvadNrVX7y0t78EnLj2Gwrk4j9Q=
  file_glob: true
  file:
    - ${TRAVIS_BUILD_DIR}/*.zip
  repo: Aspard/build-agrum
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
